language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*@dev

before_script:
  - composer self-update
  - composer require symfony/console:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source --no-interaction --no-progress

script: vendor/bin/phpunit --coverage-text
