language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 3

php:
  - 7.0

before_script:
  - wget -Ophpunit.phar https://phar.phpunit.de/phpunit-5.3.0.phar
  - composer install --dev --prefer-dist --no-interaction --no-progress

script: php phpunit.phar --coverage-text
