language: php
sudo: false

php:
  - 7.0
  - hhvm

before_script:
  - wget -Ophpunit.phar https://phar.phpunit.de/phpunit-5.3.0.phar
  - composer install --dev --prefer-source --no-interaction --no-progress

script: php phpunit.phar --coverage-text
